package com.alex.mybatis.model;

import java.util.Date;

public class Passwordresettoken {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PasswordResetToken.id
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PasswordResetToken.expiryDate
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private Date expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PasswordResetToken.token
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PasswordResetToken.user_id
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private Long user_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PasswordResetToken.id
     *
     * @return the value of PasswordResetToken.id
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PasswordResetToken.id
     *
     * @param id the value for PasswordResetToken.id
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PasswordResetToken.expiryDate
     *
     * @return the value of PasswordResetToken.expiryDate
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Date getExpiryDate() {
        return expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PasswordResetToken.expiryDate
     *
     * @param expiryDate the value for PasswordResetToken.expiryDate
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PasswordResetToken.token
     *
     * @return the value of PasswordResetToken.token
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PasswordResetToken.token
     *
     * @param token the value for PasswordResetToken.token
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PasswordResetToken.user_id
     *
     * @return the value of PasswordResetToken.user_id
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PasswordResetToken.user_id
     *
     * @param user_id the value for PasswordResetToken.user_id
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }
}