package com.alex.mybatis.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.id
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.email
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.enabled
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private Boolean enabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.firstName
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.lastName
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.password
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column User.tokenExpired
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    private Boolean tokenExpired;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.id
     *
     * @return the value of User.id
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.id
     *
     * @param id the value for User.id
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.email
     *
     * @return the value of User.email
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.email
     *
     * @param email the value for User.email
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.enabled
     *
     * @return the value of User.enabled
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.enabled
     *
     * @param enabled the value for User.enabled
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.firstName
     *
     * @return the value of User.firstName
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.firstName
     *
     * @param firstName the value for User.firstName
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.lastName
     *
     * @return the value of User.lastName
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.lastName
     *
     * @param lastName the value for User.lastName
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.password
     *
     * @return the value of User.password
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.password
     *
     * @param password the value for User.password
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column User.tokenExpired
     *
     * @return the value of User.tokenExpired
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Boolean getTokenExpired() {
        return tokenExpired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column User.tokenExpired
     *
     * @param tokenExpired the value for User.tokenExpired
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void setTokenExpired(Boolean tokenExpired) {
        this.tokenExpired = tokenExpired;
    }
}