package com.alex.mybatis.mapper;

import com.alex.mybatis.model.PersistentLogins;
import com.alex.mybatis.model.PersistentLoginsExample;
import java.util.List;

public interface PersistentLoginsDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int countByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    String insert(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    String insertSelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    List<PersistentLogins> selectByExample(PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    PersistentLogins selectByPrimaryKey(String series);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExampleSelective(PersistentLogins record, PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExample(PersistentLogins record, PersistentLoginsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByPrimaryKeySelective(PersistentLogins record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByPrimaryKey(PersistentLogins record);
}