package com.alex.mybatis.mapper;

import com.alex.mybatis.model.PersistentLogins;
import com.alex.mybatis.model.PersistentLoginsExample;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PersistentLoginsDAOImpl extends SqlMapClientDaoSupport implements PersistentLoginsDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public PersistentLoginsDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int countByExample(PersistentLoginsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("persistent_logins.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int deleteByExample(PersistentLoginsExample example) {
        int rows = getSqlMapClientTemplate().delete("persistent_logins.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int deleteByPrimaryKey(String series) {
        PersistentLogins _key = new PersistentLogins();
        _key.setSeries(series);
        int rows = getSqlMapClientTemplate().delete("persistent_logins.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public String insert(PersistentLogins record) {
        Object newKey = getSqlMapClientTemplate().insert("persistent_logins.insert", record);
        return (String) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public String insertSelective(PersistentLogins record) {
        Object newKey = getSqlMapClientTemplate().insert("persistent_logins.insertSelective", record);
        return (String) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    @SuppressWarnings("unchecked")
    public List<PersistentLogins> selectByExample(PersistentLoginsExample example) {
        List<PersistentLogins> list = getSqlMapClientTemplate().queryForList("persistent_logins.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public PersistentLogins selectByPrimaryKey(String series) {
        PersistentLogins _key = new PersistentLogins();
        _key.setSeries(series);
        PersistentLogins record = (PersistentLogins) getSqlMapClientTemplate().queryForObject("persistent_logins.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExampleSelective(PersistentLogins record, PersistentLoginsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("persistent_logins.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExample(PersistentLogins record, PersistentLoginsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("persistent_logins.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByPrimaryKeySelective(PersistentLogins record) {
        int rows = getSqlMapClientTemplate().update("persistent_logins.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByPrimaryKey(PersistentLogins record) {
        int rows = getSqlMapClientTemplate().update("persistent_logins.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table persistent_logins
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    protected static class UpdateByExampleParms extends PersistentLoginsExample {
        private Object record;

        public UpdateByExampleParms(Object record, PersistentLoginsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}