package com.alex.mybatis.mapper;

import com.alex.mybatis.model.Privilege;
import com.alex.mybatis.model.PrivilegeExample;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PrivilegeDAOImpl extends SqlMapClientDaoSupport implements PrivilegeDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public PrivilegeDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int countByExample(PrivilegeExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("Privilege.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int deleteByExample(PrivilegeExample example) {
        int rows = getSqlMapClientTemplate().delete("Privilege.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int deleteByPrimaryKey(Long id) {
        Privilege _key = new Privilege();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("Privilege.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Long insert(Privilege record) {
        Object newKey = getSqlMapClientTemplate().insert("Privilege.insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Long insertSelective(Privilege record) {
        Object newKey = getSqlMapClientTemplate().insert("Privilege.insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Privilege> selectByExample(PrivilegeExample example) {
        List<Privilege> list = getSqlMapClientTemplate().queryForList("Privilege.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Privilege selectByPrimaryKey(Long id) {
        Privilege _key = new Privilege();
        _key.setId(id);
        Privilege record = (Privilege) getSqlMapClientTemplate().queryForObject("Privilege.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExampleSelective(Privilege record, PrivilegeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("Privilege.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExample(Privilege record, PrivilegeExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("Privilege.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByPrimaryKeySelective(Privilege record) {
        int rows = getSqlMapClientTemplate().update("Privilege.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByPrimaryKey(Privilege record) {
        int rows = getSqlMapClientTemplate().update("Privilege.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    protected static class UpdateByExampleParms extends PrivilegeExample {
        private Object record;

        public UpdateByExampleParms(Object record, PrivilegeExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}