package com.alex.mybatis.mapper;

import com.alex.mybatis.model.Privilege;
import com.alex.mybatis.model.PrivilegeExample;
import java.util.List;

public interface PrivilegeDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int countByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    Long insert(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    Long insertSelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    List<Privilege> selectByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    Privilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExampleSelective(Privilege record, PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExample(Privilege record, PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByPrimaryKeySelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Privilege
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByPrimaryKey(Privilege record);
}