package com.alex.mybatis.mapper;

import com.alex.mybatis.model.RolesPrivileges;
import com.alex.mybatis.model.RolesPrivilegesExample;
import java.util.List;

public interface RolesPrivilegesDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_privileges
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int countByExample(RolesPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_privileges
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByExample(RolesPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_privileges
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    void insert(RolesPrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_privileges
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    void insertSelective(RolesPrivileges record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_privileges
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    List<RolesPrivileges> selectByExample(RolesPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_privileges
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExampleSelective(RolesPrivileges record, RolesPrivilegesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table roles_privileges
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExample(RolesPrivileges record, RolesPrivilegesExample example);
}