package com.alex.mybatis.mapper;

import com.alex.mybatis.model.UsersRoles;
import com.alex.mybatis.model.UsersRolesExample;
import java.util.List;

public interface UsersRolesDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int countByExample(UsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByExample(UsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    void insert(UsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    void insertSelective(UsersRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    List<UsersRoles> selectByExample(UsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExampleSelective(UsersRoles record, UsersRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExample(UsersRoles record, UsersRolesExample example);
}