package com.alex.mybatis.mapper;

import com.alex.mybatis.model.User;
import com.alex.mybatis.model.UserExample;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserDAOImpl extends SqlMapClientDaoSupport implements UserDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public UserDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int countByExample(UserExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("User.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int deleteByExample(UserExample example) {
        int rows = getSqlMapClientTemplate().delete("User.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int deleteByPrimaryKey(Long id) {
        User _key = new User();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("User.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Long insert(User record) {
        Object newKey = getSqlMapClientTemplate().insert("User.insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Long insertSelective(User record) {
        Object newKey = getSqlMapClientTemplate().insert("User.insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    @SuppressWarnings("unchecked")
    public List<User> selectByExample(UserExample example) {
        List<User> list = getSqlMapClientTemplate().queryForList("User.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public User selectByPrimaryKey(Long id) {
        User _key = new User();
        _key.setId(id);
        User record = (User) getSqlMapClientTemplate().queryForObject("User.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExampleSelective(User record, UserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("User.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExample(User record, UserExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("User.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByPrimaryKeySelective(User record) {
        int rows = getSqlMapClientTemplate().update("User.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByPrimaryKey(User record) {
        int rows = getSqlMapClientTemplate().update("User.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    protected static class UpdateByExampleParms extends UserExample {
        private Object record;

        public UpdateByExampleParms(Object record, UserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}