package com.alex.mybatis.mapper;

import com.alex.mybatis.model.User;
import com.alex.mybatis.model.UserExample;
import java.util.List;

public interface UserDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    Long insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    Long insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    User selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExampleSelective(User record, UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExample(User record, UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table User
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByPrimaryKey(User record);
}