package com.alex.mybatis.mapper;

import com.alex.mybatis.model.UsersRoles;
import com.alex.mybatis.model.UsersRolesExample;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UsersRolesDAOImpl extends SqlMapClientDaoSupport implements UsersRolesDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public UsersRolesDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int countByExample(UsersRolesExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("users_roles.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int deleteByExample(UsersRolesExample example) {
        int rows = getSqlMapClientTemplate().delete("users_roles.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void insert(UsersRoles record) {
        getSqlMapClientTemplate().insert("users_roles.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public void insertSelective(UsersRoles record) {
        getSqlMapClientTemplate().insert("users_roles.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    @SuppressWarnings("unchecked")
    public List<UsersRoles> selectByExample(UsersRolesExample example) {
        List<UsersRoles> list = getSqlMapClientTemplate().queryForList("users_roles.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExampleSelective(UsersRoles record, UsersRolesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("users_roles.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExample(UsersRoles record, UsersRolesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("users_roles.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users_roles
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    protected static class UpdateByExampleParms extends UsersRolesExample {
        private Object record;

        public UpdateByExampleParms(Object record, UsersRolesExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}