package com.alex.mybatis.mapper;

import com.alex.mybatis.model.Verificationtoken;
import com.alex.mybatis.model.VerificationtokenExample;
import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class VerificationtokenDAOImpl extends SqlMapClientDaoSupport implements VerificationtokenDAO {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public VerificationtokenDAOImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int countByExample(VerificationtokenExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("VerificationToken.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int deleteByExample(VerificationtokenExample example) {
        int rows = getSqlMapClientTemplate().delete("VerificationToken.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int deleteByPrimaryKey(Long id) {
        Verificationtoken _key = new Verificationtoken();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("VerificationToken.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Long insert(Verificationtoken record) {
        Object newKey = getSqlMapClientTemplate().insert("VerificationToken.insert", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Long insertSelective(Verificationtoken record) {
        Object newKey = getSqlMapClientTemplate().insert("VerificationToken.insertSelective", record);
        return (Long) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    @SuppressWarnings("unchecked")
    public List<Verificationtoken> selectByExample(VerificationtokenExample example) {
        List<Verificationtoken> list = getSqlMapClientTemplate().queryForList("VerificationToken.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public Verificationtoken selectByPrimaryKey(Long id) {
        Verificationtoken _key = new Verificationtoken();
        _key.setId(id);
        Verificationtoken record = (Verificationtoken) getSqlMapClientTemplate().queryForObject("VerificationToken.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExampleSelective(Verificationtoken record, VerificationtokenExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("VerificationToken.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByExample(Verificationtoken record, VerificationtokenExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("VerificationToken.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByPrimaryKeySelective(Verificationtoken record) {
        int rows = getSqlMapClientTemplate().update("VerificationToken.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    public int updateByPrimaryKey(Verificationtoken record) {
        int rows = getSqlMapClientTemplate().update("VerificationToken.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    protected static class UpdateByExampleParms extends VerificationtokenExample {
        private Object record;

        public UpdateByExampleParms(Object record, VerificationtokenExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}