package com.alex.mybatis.mapper;

import com.alex.mybatis.model.Verificationtoken;
import com.alex.mybatis.model.VerificationtokenExample;
import java.util.List;

public interface VerificationtokenDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int countByExample(VerificationtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByExample(VerificationtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    Long insert(Verificationtoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    Long insertSelective(Verificationtoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    List<Verificationtoken> selectByExample(VerificationtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    Verificationtoken selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExampleSelective(Verificationtoken record, VerificationtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByExample(Verificationtoken record, VerificationtokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByPrimaryKeySelective(Verificationtoken record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VerificationToken
     *
     * @mbggenerated Wed Dec 16 13:41:24 GMT 2015
     */
    int updateByPrimaryKey(Verificationtoken record);
}